// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgzwLmjFHuAMrACC6--9Hbz8B6oWZ9to8',
    appId: '1:623408932792:web:efc241f52f45069b42514d',
    messagingSenderId: '623408932792',
    projectId: 'm-and-r-education',
    authDomain: 'm-and-r-education.firebaseapp.com',
    storageBucket: 'm-and-r-education.appspot.com',
    measurementId: 'G-ZQKW8SRBM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5tyJqvs1pUdvtRHj2rW34mFqfHRYonCM',
    appId: '1:623408932792:android:59621d842d29224542514d',
    messagingSenderId: '623408932792',
    projectId: 'm-and-r-education',
    storageBucket: 'm-and-r-education.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7n4blOzc0iFFges2LxXhIJlfNw8Nd7dU',
    appId: '1:623408932792:ios:ba53ac5a54c3c02042514d',
    messagingSenderId: '623408932792',
    projectId: 'm-and-r-education',
    storageBucket: 'm-and-r-education.appspot.com',
    iosBundleId: 'com.mr.quiz.mAndRQuizAdminPanel',
  );

}